# docker-compose.yml

version: '3.8'

services:
  # Redis service
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

  # Celery worker service
  celery_worker:
    build: .
    container_name: celery_worker
    command: celery -A celeryconfig.app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - CELERY_BROKER=redis://redis:6379/0

  # Producer (could be a separate service or just a task)
  producer:
    build: .
    container_name: celery_producer
    command: celery -A celeryconfig.app worker --loglevel=info
    depends_on:
      - redis

  # The default is to run Celery tasks, so there is no need for a web service

volumes:
  redis_data:
    driver: local
